---
# tasks file for launch_instances
- name: "launching Master Node for kubernetes ..."
  ec2_instance:
        region: "{{ reg }}"
        image_id: "{{ img_id }}"
        instance_type: "{{ i_type }}"
        vpc_subnet_id: "{{ vpcsi }}"
        key_name: "{{ key }}"
        security_group: "{{ sg_group }}"
        name: "K8S_Master"
        state: present
        aws_access_key: "{{ aws_ak }}"
        aws_secret_key: "{{ aws_sk }}"
        volumes:
        - device_name: "/dev/xvda"
          ebs:
             volume_size: "{{ vol_size }}"
             delete_on_termination: true
        tags:
             name: "Master"

- name: "launching Master Node for kubernetes ..."
  ec2_instance:
        region: "{{ reg }}"
        image_id: "{{ img_id }}"
        instance_type: "{{ i_type }}"
        vpc_subnet_id: "{{ vpcsi }}"
        key_name: "{{ key }}"
        security_group: "{{ sg_group }}"
        name: "Slave1"
        state: present
        aws_access_key: "{{ aws_ak }}"
        aws_secret_key: "{{ aws_sk }}"
        volumes:
        - device_name: "/dev/xvda"
          ebs:
             volume_size: "{{ vol_size }}"
             delete_on_termination: true
        tags:
             name: "Slave"
             node: "Slave1"
		

- name: "launching Master Node for kubernetes ..."
  ec2_instance:
        region: "{{ reg }}"
        image_id: "{{ img_id }}"
        instance_type: "{{ i_type }}"
        vpc_subnet_id: "{{ vpcsi }}"
        key_name: "{{ key }}"
        security_group: "{{ sg_group }}"
        name: "Slave2"
        state: present
        aws_access_key: "{{ aws_ak }}"
        aws_secret_key: "{{ aws_sk }}"
        volumes:
        - device_name: "/dev/xvda"
          ebs:
             volume_size: "{{ vol_size }}"
             delete_on_termination: true
        tags:
             name: "Slave"
             node: "Slave2"


