---
# tasks file for wordpress-mysql
# task to launch Woedpress
- name: "Launching Wordpress"
  shell: "kubectl run mywp1 --image=wordpress:5.1.1-php7.3-apache"
  register: Wordpress
- debug:
    var: "Wordpress.stdout_lines"

#task to launch mysql 
- name: "Launching MySql"
  shell: "kubectl run mydb1 --image=mysql:5.7 --env=MYSQL_ROOT_PASSWORD=rootPassword     --env=MYSQL_DATABASE=vinod_db  --env=MYSQL_USER=vinod  --env=MYSQL_PASSWORD=yourPassword"
  register: MySql

- name: "Exposing wordpess"
  shell: "kubectl expose pods mywp1  --type=NodePort   --port=80"
  register: expose
  ignore_errors: yes

- debug: 
    var: "expose.stdout_lines"

- name: "get service"
  shell: "kubectl get svc"
  register: svc

- debug:
    var: "svc.stdout_lines"

- name: "Pausing playbook for 60 seconds"
  pause: 
    seconds: 30

- name: "getting database IP"
  shell: "kubectl get pods -o wide"
  register: Database_IP

- debug:
    var: "Database_IP.stdout_lines"
